### ISSUE TITLE
Rework benchmarks to only measure correct area of code

### ISSUE THREAD

**Issue by avborup** [Tietgen-ITU/cosyp_project#12]
Discord message:

> Jeg har lige snakket med Pinar om hvad vi skal gøre med partitions efter vi har genereret dem - skal vi bare deallokere dem eller noget andet? Det førte til en mere uddybende samtale om vores benchmarks generelt, og vi fandt ud af at artiklen faktisk ikke tæller noget som helt memory allocation med. I artiklen allokerer de alt memory først, profiler, og så deallokerer. Dvs. benchmarken måler kun selve det at finde hvilken partition tuples skal ende i samt at flytte dem over.
> 
> Så vi skal nok også lige reworke den måde vi benchmarker 😅  Men det burde være super nemt.

**Comment by Arneproductions** [comment]
@avborup How far are you with this one?

**Comment by avborup** [comment]
It's done IIRC
